version: '2'
services:
  nest:
    container_name: hedwig-nest
    restart: always
    image: genee/hedwig-nest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./etc/hedwig:/etc/hedwig
