beanstalkd:
  image: schickling/beanstalkd:latest
  restart: always
  ports:
    - 172.17.0.1:11300:11300
  container_name: beanstalkd
  log_driver: none
doorman:
  container_name: doorman
  restart: always
  build: .
  dockerfile: doorman/Dockerfile
  ports:
    - 80:80
  volumes:
    - ./doorman/:/usr/app/
    - /etc/localtime:/etc/localtime:ro
  links:
    - beanstalkd:beanstalkd
  log_driver: none
dispatcher:
  container_name: dispatcher
  restart: always
  build: .
  dockerfile: dispatcher/Dockerfile
  volumes:
    - ./dispatcher/:/usr/app/
    - /etc/localtime:/etc/localtime:ro
  links:
    - beanstalkd:beanstalkd
  log_driver: none
send_worker:
  container_name: send_worker
  restart: always
  build: .
  dockerfile: send_worker/Dockerfile
  volumes:
    - ./send_worker/:/usr/app/
    - /etc/localtime:/etc/localtime:ro
  links:
    - beanstalkd:beanstalkd
  log_driver: none
trash_worker:
  container_name: trash_worker
  restart: always
  build: .
  dockerfile: trash_worker/Dockerfile
  volumes:
    - ./trash_worker/:/usr/app/
    - /etc/localtime:/etc/localtime:ro
  links:
    - beanstalkd:beanstalkd
  log_driver: none
