beanstalkd:
  image: schickling/beanstalkd:latest
  restart: always
  ports:
    - 172.17.0.1:11300:11300
  container_name: beanstalkd
  log_driver: none
doorman:
  container_name: doorman
  restart: always
  build: .
  dockerfile: Dockerfile.doorman
  ports:
    - 80:80
  volumes:
    - ./:/usr/app/
    - /etc/localtime:/etc/localtime:ro
  links:
    - beanstalkd:beanstalkd
  log_driver: none
send:
  container_name: send
  restart: always
  build: .
  dockerfile: Dockerfile.send
  volumes:
    - ./:/usr/app/
    - /etc/localtime:/etc/localtime:ro
  links:
    - beanstalkd:beanstalkd
  log_driver: none
