postoffice:
  container_name: postoffice
  restart: always
  build: .
  ports:
    - 80:80
  volumes:
    - ./:/usr/app/
    - /etc/localtime:/etc/localtime:ro
  log_driver: none
  links:
    - beanstalkd:beanstalkd
beanstalkd:
  image: schickling/beanstalkd:latest
  restart: always
  ports:
    - 172.17.42.1:11300:11300
  container_name: beanstalkd
  log_driver: none